name: Test

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #windows-latest
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install

    - name: Run tests
      env:
        TV_USERNAME: ${{ secrets.TV_USERNAME }}
        TV_PASSWORD: ${{ secrets.TV_PASSWORD }}
      run: poetry run pytest
